name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Verify and inject Agora App ID
        env:
          AGORA_APP_ID: ${{ secrets.AGORA_APP_ID }}
        run: |
          if [ -z "$AGORA_APP_ID" ]; then
            echo "✗ AGORA_APP_ID is not set"
            exit 1
          fi
          
          # Create a temporary index file with the App ID injected
          sed "s|</head>|<script>window.AGORA_APP_ID = '${AGORA_APP_ID}';</script></head>|" index.html > index.tmp.html
          mv index.tmp.html index.html

      - name: Prepare deployment files
        run: |
          mkdir -p deploy
          cp index.html deploy/
          cp styles.css deploy/
          cp app.js deploy/
          cp README.md deploy/

      - name: Upload deployment artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: deploy

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2